DB_NAME=salesync_record_service
DB_HOST=localhost
DB_PORT=54323
DB_USER=record_service
DB_PASSWORD=record_service

RABBITMQ_HOST=localhost
RABBITMQ_PORT=5672
RABBITMQ_USER=salesync
RABBITMQ_PASSWORD=salesync

ELASTICSEARCH_HOST=localhost
ELASTICSEARCH_PORT=9200
ELASTICSEARCH_INDEX=records
ELASTICSEARCH_PROTOCOL=http

TOKEN_KEY_LOCATION=/home/secrets/auth-publickey.pem
TYPE_SERVICE_ENDPOINT=http://localhost:5000



